### ISSUE TITLE
Shows only one version at a time

### ISSUE THREAD

**Issue by PokerAsh** [MFlisar/changelog#11]
For instance, I've got 5 buttons on a view. Each button has it's own versionName. Whenever user clicks on a button, dialog pops up on a corresponding version,  and only that version will be shown, not others.

**Comment by MFlisar** [comment]
Use a custom filter like following e.g.:

    class VersionFilter(val version: Int) : IChangelogFilter, Parcelable {
        override fun checkFilter(item: IRecyclerViewItem?): Boolean = item is IChangelogEntry && item.versionCode == version || !(item is IChangelogEntry) 
        
        constructor(parcel: Parcel) : this(parcel.readInt())

        override fun writeToParcel(parcel: Parcel, flags: Int) {
            parcel.writeInt(version)
        }

        override fun describeContents(): Int = 0

        companion object CREATOR : Parcelable.Creator<VersionFilter> {
            override fun createFromParcel(parcel: Parcel): VersionFilter {
                return VersionFilter(parcel)
            }

            override fun newArray(size: Int): Array<VersionFilter?> {
                return arrayOfNulls(size)
            }
        }
    }

**Comment by PokerAsh** [comment]
TYVM. Now I've got another situation. Whenever, I click on version button, dialog title always "Changelog" + versionName of my BuildGradle.VERSION_NAME. Is it possible to change? Everytime whenever I try 
builder1.buildAndShowDialog(mActivity, false).getDialog().setTitle(version1Name), gives me NPE

**Comment by MFlisar** [comment]
You can try the current master branch:

     implementation 'com.github.MFlisar:changelog:-SNAPSHOT'

Then you have a new method for the builder `withTitle("some custom title")` you can use...

**Comment by PokerAsh** [comment]
Cool. Thank you

**Comment by MFlisar** [comment]
Can use `v1.1.1` now as well
