### ISSUE TITLE
AndroidX migration

### ISSUE THREAD

**Issue by PokerAsh** [MFlisar/changelog#12]
My project leads don't want to migrate to AndroidX yet. So, is it possible to let people use either appCompat version or androidx? In buildAndShowDialog(appCompatActivity, false)?

**Comment by MFlisar** [comment]
You have 2 choices:

- stay with an old version (`1.0.5`), it's working fine, there are no bugfixes added, just small new features
- fork and simply change the imports

I don't know a way to combine androidx and appcompat in one project and make this configurable
