### ISSUE TITLE
Suggestion - add support for line breaks and other formatting

### ISSUE THREAD

**Issue by ahctang** [MFlisar/changelog#14]
Adding support for something like CDATA within the new, info, etc. tags would make the library much easier to use!

**Comment by MFlisar** [comment]
HTML tags are supported for example, but must be used like following:

    <new>[b][font color="#009933"]Awesome features added![/font][/b] Awesome features description</new>

This is supported by the XML parser itself already

**Comment by MFlisar** [comment]
I assume the html tags are sufficient for now due to no respone, so I close this
