### ISSUE TITLE
How to implement this in a complete activity as it appears in the screenshots?

### ISSUE THREAD

**Issue by Okami-x-Senpai** [MFlisar/changelog#16]
I would like a guide to be able to implement it this way, because the example I see in the **/demo folder** _only shows how to open it in the form of Dialog,_ but not in **_full activity as seen in some screenshots._** _Could you help me, Mr. Developer?_

**Comment by MFlisar** [comment]
Check out this line in the demo

https://github.com/MFlisar/changelog/blob/c99f91370772e761ef078c9309e2e7b8d51c8e47/demo/src/main/java/com/michaelflisar/changelog/demo/MainActivity.java#L110

Check the code around it to see how to set up the activity, the line above will start an `activity` instead of a `dialog`

**Comment by Okami-x-Senpai** [comment]
I did what is in the example that showed me, but when I enter the activity does nothing.

This is my code:
```
public class Changelog extends AppCompatActivity implements IChangelogRateHandler {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main_changelog);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        ChangelogBuilder builder = new ChangelogBuilder()
                .withUseBulletList(true)
                .withManagedShowOnStart(true)
                .withRateButton(true)
                .withRateButtonLabel("¿Te gusto esta actualizacion?")
                .withSummary(true, true);
        builder.buildAndStartActivity(this, true);

    }

    @Override
    public boolean onRateButtonClicked() {
        return false;
    }
}
```

**Comment by MFlisar** [comment]
Either remove this line

    .withManagedShowOnStart(true)

Or increase your app version number. Above line will make sure to show the changelog ONCE only per app version...
