### ISSUE TITLE
How can I use this dependency with Java 7?

### ISSUE THREAD

**Issue by Okami-x-Senpai** [MFlisar/changelog#17]
My application has at least **Java 7** but when I try to compile the APK it **tells me that I have to have minimum Java (8)**.

**Comment by MFlisar** [comment]
I would say nothing speaks against using JAVA 8, check out this lines in the demo to see how to enable java 8 in your own project:

https://github.com/MFlisar/changelog/blob/c99f91370772e761ef078c9309e2e7b8d51c8e47/demo/build.gradle#L21-L24

**Comment by MFlisar** [comment]
Btw, you can simply remove the java 8 dependency by replacing all the lambdas in my library (probably not more than 10 anyways) if you want to... but I won't do this because if I make a larger change in the future I will convert the library to kotlin anyways...

**Comment by Okami-x-Senpai** [comment]
Is that **I do not use Java 8**  because **lambda makes me very ugly** . But when trying to use this dependency Java 8 asks me. _Any way to use Java 8 without using Lambda? _

**Comment by MFlisar** [comment]
Sure, simply use java8. It still supports all language features of java7 but only *adds* lambda support and more... you are not forced to use lambdas but personally I would suggest trying them...
