### ISSUE TITLE
Overriding DialogFragment style

### ISSUE THREAD

**Issue by bwalsh0** [MFlisar/changelog#18]
I'm using 
```java
builder.buildAndShowDialog(AppCompatActivity, darkTheme);
```
and my application's style derives attributes from `Theme.MaterialComponents.Light` instead of `Theme.AppCompat.Light` as the library does, so the dialog buttons are styled/colored incorrectly. (Such as the "Ok" and "Rate" buttons).

In the lib source, I found the line:
```java
dlg.setStyle(DialogFragment.STYLE_NORMAL, darkTheme ? 
R.style.ChangelogDialogDarkTheme : R.style.ChangelogDialogLightTheme);
```

but defining my own in my `styles.xml` doesn't change anything:
```xml
<style name="ChangelogDialogLightTheme" parent="@style/Theme.AppCompat.Light.Dialog">
    <item name="android:dialogTheme">@style/Theme.MaterialComponents.Light.Dialog</item>
</style>
```
(Amongst other variations I've tried, using my own parent style, etc.)

Is this something that isn't possible with the DialogFragment, or am I doing something incorrectly?

Thanks.

**Comment by MFlisar** [comment]
You can simply override `R.style.ChangelogDialogDarkTheme` and `R.style.ChangelogDialogLightTheme` in your styles.

Actually, the "wrong" theme is just something I did oversee, will change this in the next update

**Comment by bwalsh0** [comment]
Glad to hear it - thanks for your work.

**Comment by MFlisar** [comment]
Changed in [v1.1.6](https://github.com/MFlisar/changelog/releases/tag/1.1.6)

**Comment by bwalsh0** [comment]
For anyone who comes across this in the future, I was able to specifically change the dialog button style in styles.xml by overriding:

```xml
<style name="Widget.MaterialComponents.Button" parent="Widget.MaterialComponents.Button.UnelevatedButton">
    <!--Custom styles here-->
</style>
```
Note that this will affect the standard `Button` class as well if you use that instead of `MaterialButton`
