### ISSUE TITLE
How to support multi-language.

### ISSUE THREAD

**Issue by rolloaxel** [MFlisar/changelog#19]
Hey,

Thanks for this repo, very helpfull,
But I need the solution to be translatable...

It is possible?

**Comment by MFlisar** [comment]
Sure, just like any resource you can put the changelog files in their corresponding resource files: https://developer.android.com/guide/topics/resources/localization

Like e.g. put the xml file into:

   * raw
   * raw-de
   * raw-fr
   * raw-it
  * ...
