### ISSUE TITLE
Rating and Ok buttons wont show in builder.buildAndStartActivity

### ISSUE THREAD

**Issue by RM-bit** [MFlisar/changelog#22]
Like in object using builder.buildAndStartActivity rating and OK buttons dont show up in changelog, they work properly in builder.buildAndShowDialog.
Bug? or I made something wrong?
thats my code:
ChangelogBuilder builder = new ChangelogBuilder()

                .withTitle("Note Aggiornamento")
                .withRateButton(true)
                .withRateButtonLabel("Votami")
                .withOkButtonLabel("OK")
                .withUseBulletList(true);

        builder.buildAndShowDialog(this, true);
thanks
riccardo

**Comment by MFlisar** [comment]
There is no ok button in the activity - you have the back button in the activities toolbar instead.

I'll add the rate button to the activity, but it won't support a custom behaviour. Feel free to add this in a future pull request.
