### ISSUE TITLE
rethink your screenshots

### ISSUE THREAD

**Issue by hannesa2** [MFlisar/changelog#5]
I know it's unimportant, but what's about rethink the color in your README.md screenshots
It remembers to websites in the '90 and does not reflect the cool and modern library you created

<img width="129" alt="image" src="https://user-images.githubusercontent.com/3314607/38974180-6a22b302-43a9-11e8-8071-fe1f90819a9c.png">

I know taste makes sometimes lonesome

**Comment by MFlisar** [comment]
Actually, I personally only use new/bugfix/info tags, made the rest just for fun...

What colors would you suggest for a more clean look? I don't like the colors that much either, red/green are just the default colors I would link with "new" and "bug"...

**Comment by hannesa2** [comment]
e.g gabrielemariotti's color don't cry that much

**Comment by MFlisar** [comment]
So just bold texts, no color

**Comment by MFlisar** [comment]
Just screenshots, not that important ;-)
