### ISSUE TITLE
Is it possible to use on Fragments?

### ISSUE THREAD

**Issue by mrfanatic** [MFlisar/changelog#6]
`.buildAndShowDialog(getActivity(), false);` is not working.
Wrong argument, found AppCompatActivity.

**Comment by MFlisar** [comment]
A `AppCompatActivity` should work (check here: https://github.com/MFlisar/changelog/blob/master/lib/src/main/java/com/michaelflisar/changelog/ChangelogBuilder.java#L300). Are you using the default activities? Then this is not supported.

Using it from a support fragment is possible though...

**Comment by mrfanatic** [comment]
what i mean is, can i use like this:
```
public class MyClass extends Fragment {
//...
ChangelogBuilder builder = new ChangelogBuilder();
builder.withUseBulletList(true);
//...
}
```

**Comment by MFlisar** [comment]
Following works:

```java
public class MyCompatFragment extends android.support.v4.app.Fragment {
    private void showChangelog() {
        new ChangelogBuilder()
            .withUseBulletList(true)
            .buildAndShowDialog(getActivity(), false);
    }
}
```

Following **won't** work:


```java
public class MyCompatFragment extends android.app.Fragment {
    private void showChangelog() {
        new ChangelogBuilder()
            .withUseBulletList(true)
            .buildAndShowDialog(getActivity(), false);
    }
}
```

As I wrote, it only works with the support library (check `android.support.v4.app.Fragment` vs `android.app.Fragment` in the code above).

So you need to use `android.support.v7.app.AppCompatActivity` with `android.support.v4.app.Fragment` for this library.

**Comment by mrfanatic** [comment]
Thank you very much.
