### ISSUE TITLE
Crash launching activity

### ISSUE THREAD

**Issue by gonemad** [MFlisar/changelog#7]
Got a crash report of the following exception from a nexus 4 running 6.0.1.  Apparently getSupportActionBar is null

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setTitle(java.lang.CharSequence)' on a null object reference
       at com.michaelflisar.changelog.internal.ChangelogActivity.onCreate(ChangelogActivity.java:43)
       at android.app.Activity.performCreate(Activity.java:6280)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by MFlisar** [comment]
Do you use a custom theme for the activity? If so make sure you use a theme with an action bar...

Is this the issue here?

**Comment by gonemad** [comment]
Perhaps. I have toobars but they are in the fragments and are assigned to the activity in code. A changelog dialog shouldn't require a toolbars tho (I also don't want the title to be changed regardless). Could you make that optional

**Comment by MFlisar** [comment]
The dialog does not require one...

The activity does not have a title element by default, so you need to add one. Either by theme (what the activity mode here assumes) or manually...

Extending this means, you must provide in the builder if the activity's theme has a toolbar or not though...

**Comment by MFlisar** [comment]
This release solves the issue: [v1.0.2](https://github.com/MFlisar/changelog/releases/tag/1.0.2)

**Comment by gonemad** [comment]
I'm only using the dialog... Either way thanks for the fix

**Comment by MFlisar** [comment]
your log says `ChangelogActivity.onCreate(ChangelogActivity.java:43)`

If you use `buildAndShowDialog` a dialog will be shown, if you use  `buildAndStartActivity` an activity will be started... Crash log can only occur with second option...

**Comment by gonemad** [comment]
This is my code and i am as confused as you why i received multiple crash reports about an activity.  I could not use buildAndShowDialog since it only accepted an activity as a parameter.. i was doing this in a nested fragment.  The code is in kotlin

```
val builder = ChangelogBuilder().withUseBulletList(true)

val dialog = ChangelogDialogFragment.create(builder, GMThemeEngine.getInstance(context).currentTheme.isDark)
dialog.show(this.fragmentManager, ChangelogDialogFragment::class.java.name)
```

**Comment by MFlisar** [comment]
Weird. Check out this class:

https://github.com/MFlisar/changelog/blob/master/lib/src/main/java/com/michaelflisar/changelog/internal/ChangelogDialogFragment.java

It's a simple fragment (support fragment). Nothing in there can trigger anything in the activity class...

Can you reproduce this? Are you sure the above usage it the one triggering the crash or the only way you use it?

**BTW**

You should be able to use `builder.buildAndShowDialog(this.activity, GMThemeEngine.getInstance(context).currentTheme.isDark)`...

**Comment by gonemad** [comment]
My app is a single activity with fragments so no where in my code am i creating another activity.  For now i'll just assume the crash report i got came from some user who tried modifying the code?  Not going to worry about it for now unless i start seeing a lot more from multiple users.

buildAndShowDialog would not work for me because of the nested fragments.  The code would crash using this.activity.  From what i remember of the stack trace.. it did not like using the activity's fragment manager, which is why i pass the fragment manager of the nested fragment in.  I'll see if i can recreate the crash and open another issue for it
