### ISSUE TITLE
Configurable buttons on changelog dialog

### ISSUE THREAD

**Issue by gonemad** [MFlisar/changelog#8]
This is more of a feature request.

It would be nice if i could add a customizable button to the changelog dialog.  I do not like to bother users by having popups asking them to rate my app, so in the past i've typically added a rate button to my changelog area.  Having the option to add an additional button would allow me to do that (assuming i could just pass in a click listener to handle the button press)

**Comment by MFlisar** [comment]
Handler is problematic, but I could define a callback interface that the parent activity needs to implement which will be called if the button is clicked - the standard thing for fragment <-> activity communication...

**Comment by gonemad** [comment]
What do you mean by "Handler is problematic".  If it took an callback interface as an input (instead of forcing the parent activity to implement something which does not work very well if your using MVP with a single activity) that would work fine.  I was thinking the AlertDialog's neutral or negative button could be leveraged

**Comment by MFlisar** [comment]
This is a `DialogFragment`, no `AlertDialog`. It survices rotation e.g.... All the data passed to it must be parcelable. That's why the builder is parcelable...

It should be possible to check if the parent activity or the parent fragment implements the callback interface, but that's the only solution I can think of (other than buses or similar, which is not part of the library, and it should work without them as well)

**Comment by gonemad** [comment]
ah yea.. that makes sense

okay so i propose you do the callback interface that the activity would have to support and also add the ability to pass in a fragment that implements the interface as well.  Under the hood the activity is only used to get the support manager.  As mentioned before my app is a single activity with tons of fragments so i would like to keep all the of the logic for the fragment that is going to show the changelog inside that fragment (or.. well the presenter of the fragment).  I believe you can leverage 

https://developer.android.com/reference/android/app/Fragment#settargetfragment

to access the fragment that created the dialogfragment

Example:
https://gist.github.com/Joev-/5695813

**Comment by MFlisar** [comment]
Would you mind adding this with the callback and create a pull request? Feel free to make it the way you like it, I may make adjustments afterwards... (like support for parent activity, maybe layout adjustments, whatever).

**Comment by gonemad** [comment]
Yeah I can take a stab at it

**Comment by MFlisar** [comment]
I added `withRateButton(true)` and the `IChangelogRateHandler`, check out this to see the implementation: 

https://github.com/MFlisar/changelog/blob/e4d5ca5449bffb5114a3f4fae5fcdb1246034bfd/lib/src/main/java/com/michaelflisar/changelog/internal/ChangelogDialogFragment.java#L53-L70

And

https://github.com/MFlisar/changelog/blob/e4d5ca5449bffb5114a3f4fae5fcdb1246034bfd/lib/src/main/java/com/michaelflisar/changelog/internal/ChangelogDialogFragment.java#L86-L90

New feature is added in this release: https://github.com/MFlisar/changelog/releases/tag/1.0.3

**Comment by MFlisar** [comment]
PS: v1.0.4 will open the play store link by default, no need to implement the callback if you want this default behaviour
