### ISSUE TITLE
ManagedShowOnStart make the dialog skip.

### ISSUE THREAD

**Issue by SuppaMan150** [MFlisar/changelog#9]
Hi!
I assume the feature would show the dialog only one time and never again.
In my situation, instead, the dialog isn't ever showed, and also the first time in the log appears "I/Changelog Library: Showing changelog dialog skipped".
How can I fix this?
Thanks

**Comment by MFlisar** [comment]
You probably just did not update the app version? It will show the changelog once for an app version only

**Comment by MFlisar** [comment]
Reopen if you still have problems
